[tool.poetry]
name = "glacier-machine-data-model"
version = "0.0.0"
description = "Machine data model for the Glacier platform."
authors = ["Sebastiano Gaiardelli <sebastiano.gaiardelli@univr.it>"]
license = "BSD-2-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0.2"


[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
radon = "^6.0.1"
isort = "^5.13.2"
flake8 = "^7.1.1"
lizard = "^1.17.13"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
